import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.dirname(fileURLToPath(import.meta.url));
const data = JSON.parse(await readFile(path.join(root, 'content.json'), 'utf8'));
const out = path.join(root, 'dist');
await mkdir(path.join(out, 'actualites'), { recursive: true });
await mkdir(path.join(out, 'assets'), { recursive: true });
const esc = (s) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = s => new Intl.DateTimeFormat('fr-FR', {day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(s + 'T12:00:00Z'));
const svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="18" fill="#091321"/><circle cx="28" cy="34" r="16" fill="none" stroke="#81efe0" stroke-width="5"/><circle cx="46" cy="16" r="6" fill="#b9a1ff"/></svg>';
const favicon = 'data:image/svg+xml,' + encodeURIComponent(svg);
const arrow = '<span aria-hidden="true">↗</span>';
if (data.leetchiUrl) {
  const url = new URL(data.leetchiUrl);
  if (url.protocol !== 'https:' || !['leetchi.com','www.leetchi.com'].includes(url.hostname) || url.pathname === '/') throw new Error('Une URL HTTPS de cagnotte Leetchi est requise.');
}
for (const n of data.news) if (!/^[a-z0-9-]+$/.test(n.slug)) throw new Error('Slug invalide');
data.news.sort((a,b) => b.date.localeCompare(a.date));
const nav = (prefix = './', article = false) => `<header class="header"><a class="brand" href="${prefix}" aria-label="SporeMP, accueil"><span class="brand-icon" aria-hidden="true">◌</span>spore<span>mp</span></a><nav aria-label="Navigation principale"><a href="${prefix}#projet">Le projet</a><a href="${prefix}#actualites" ${article ? 'aria-current="page"' : ''}>Actualités</a><a href="${prefix}#versions">Mises à jour</a><a href="${prefix}#avenir">À venir</a></nav><a class="support-link" href="${prefix}#soutenir">Soutenir <span aria-hidden="true">♡</span></a></header>`;
const footer = prefix => `<footer class="footer wrap"><a class="brand" href="${prefix}">spore<span>mp</span></a><p>Un projet indépendant, animé par l’envie de jouer ensemble.</p><a href="${prefix}#projet">Retour au projet ↑</a><div class="fineprint">Projet communautaire non officiel, non affilié à Electronic Arts ou Maxis. SPORE appartient à ses ayants droit.<br>Illustration originale du projet, générée par IA ; elle ne représente pas une capture du multijoueur. Aucun outil de suivi publicitaire.</div></footer>`;
const shell = ({title, description, body, prefix='./', canonical=''}) => `<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="dark"><meta name="theme-color" content="#070c15"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(data.siteUrl + canonical)}"><meta property="og:type" content="${canonical ? 'article' : 'website'}"><meta property="og:locale" content="fr_FR"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(data.siteUrl + canonical)}"><link rel="icon" type="image/svg+xml" href="${favicon}"><link rel="stylesheet" href="${prefix}styles.css"></head><body><a class="skip-link" href="#contenu">Aller au contenu</a>${body}<script src="${prefix}site.js" defer></script></body></html>`;
const newsCards = data.news.map((n,i) => `<article class="news-card"><div class="news-meta"><span>${esc(n.category)}</span><time datetime="${n.date}">${date(n.date)}</time></div><span class="editorial-number" aria-hidden="true">0${i+1}</span><h3><a href="./actualites/${n.slug}.html">${esc(n.title)}</a></h3><p>${esc(n.summary)}</p><a class="text-link" href="./actualites/${n.slug}.html" aria-label="Lire l’article : ${esc(n.title)}">Lire le journal ${arrow}</a></article>`).join('');
const releases = data.releases.map((r,i) => `<details class="release" ${i === 0 ? 'open' : ''}><summary><span class="version">v${esc(r.version)}</span><span class="release-title">${esc(r.title)}<time datetime="${r.date}">${date(r.date)}</time></span><span class="expand" aria-hidden="true">+</span></summary><div class="release-body"><ul>${r.changes.map(c=>`<li>${esc(c)}</li>`).join('')}</ul><p class="release-note">${esc(r.note)}</p></div></details>`).join('');
const roadmap = data.roadmap.map((r,i)=>`<li class="roadmap-step"><span class="step-number">0${i+1}</span><div><span class="tag ${i===0?'next':''}">${esc(r.status)}</span><h3>${esc(r.title)}</h3><p>${esc(r.description)}</p></div></li>`).join('');
const support = data.leetchiUrl ? `<a class="button primary" href="${esc(data.leetchiUrl)}" target="_blank" rel="noopener noreferrer">Faire un don sur Leetchi ${arrow}</a><p class="support-note">Don libre et facultatif, directement sur Leetchi.</p>` : '<p class="donation-pending">La cagnotte Leetchi sera annoncée ici.</p>';
const body = `${nav()}<main id="contenu"><section class="hero" aria-labelledby="hero-title"><img class="hero-art" src="./assets/universe.png" width="1536" height="1024" alt="Deux créatures contemplent une planète lumineuse depuis un monde extraterrestre." fetchpriority="high"><div class="hero-shade"></div><div class="hero-content wrap"><p class="eyebrow"><span class="status-dot"></span> Un projet en évolution</p><h1 id="hero-title">L’évolution,<br>ça se partage.</h1><p class="hero-description">Le rêve de vivre SPORE à plusieurs.<br>Un même univers. Votre propre histoire.</p><div class="hero-actions"><a class="button primary" href="#projet">Découvrir le projet <span aria-hidden="true">↓</span></a><a class="button ghost" href="#actualites">Les dernières nouvelles ${arrow}</a></div><p class="hero-note">Mod indépendant · En développement · Windows</p></div><div class="hero-caption">ILLUSTRATION DU PROJET</div></section>
<div class="development-strip wrap"><span class="tag">Au fil du développement</span><p>Premiers déplacements partagés testés dans l’étape Créature.</p><a href="./actualites/premiere-scene-partagee.html">Voir l’avancée ${arrow}</a></div>
<section class="section wrap project" id="projet" aria-labelledby="project-title"><div><p class="eyebrow muted">01 / L’idée</p><h2 id="project-title">Votre espèce.<br>Notre univers.</h2></div><div class="project-copy"><p class="large-copy">Et si votre prochaine rencontre dans SPORE était un autre joueur ?</p><p>SporeMP est un projet de mod multijoueur pour le jeu original. Son ambition : parcourir ensemble les cinq étapes de l’évolution, de la Cellule à l’Espace, dans un univers qui continue de vivre après votre départ.</p><p>Chacun pourra suivre sa propre évolution, explorer à son rythme et croiser les autres. Les créatures, les éditeurs et les mécaniques du SPORE original restent au cœur du projet.</p><div class="current-status"><span class="tag next">Où en est-on ?</span><p>Les premiers déplacements et la reconnexion ont été testés dans une scène Créature. La campagne multijoueur complète est encore en développement. Aucune date de sortie publique n’est annoncée.</p></div></div><div class="evolution" aria-label="Les cinq étapes visées par le projet"><span>01 <b>Cellule</b></span><span>02 <b>Créature</b><small>Premiers essais</small></span><span>03 <b>Tribu</b></span><span>04 <b>Civilisation</b></span><span>05 <b>Espace</b></span></div></section>
<section class="section news-section" id="actualites" aria-labelledby="news-title"><div class="wrap"><div class="section-heading"><div><p class="eyebrow muted">02 / Le journal</p><h2 id="news-title">L’aventure se construit.</h2></div><p>Des nouvelles du projet,<br>une avancée à la fois.</p></div><div class="news-grid">${newsCards}</div></div></section>
<section class="section wrap releases-section" id="versions" aria-labelledby="release-title"><div><p class="eyebrow muted">03 / Les mises à jour</p><h2 id="release-title">Chaque détail<br>compte.</h2><p class="section-intro">Les dernières évolutions du launcher et des outils qui préparent le multijoueur.</p><p class="small-note">Versions de développement sélectionnées.<br>Pas encore de téléchargement public.</p></div><div class="releases">${releases}</div></section>
<section class="section wrap" id="avenir" aria-labelledby="future-title"><div class="section-heading"><div><p class="eyebrow muted">04 / La suite</p><h2 id="future-title">Un univers à construire.</h2></div><p>Une direction claire.<br>Pas de date promise.</p></div><ol class="roadmap">${roadmap}</ol><p class="roadmap-note">Ces étapes décrivent les objectifs à venir. Leur réalisation dépend des essais dans le jeu original.</p></section>
<section class="support-section wrap" id="soutenir" aria-labelledby="support-title"><div class="support-inner"><div><p class="eyebrow">05 / Un coup de pouce</p><h2 id="support-title">Vous aimez<br>la direction ?</h2></div><div><p>SporeMP est un projet indépendant en développement. Si vous souhaitez soutenir cette aventure, un don libre peut lui donner un coup de pouce.</p><p>Le soutien reste entièrement facultatif et ne constitue ni un achat ni une promesse de date de sortie.</p>${support}</div></div></section></main>${footer('./')}`;
await writeFile(path.join(out,'index.html'), shell({title:'SporeMP — L’évolution, ça se partage.',description:'Découvrez SporeMP, le projet de multijoueur pour le SPORE original. Actualités, mises à jour et feuille de route, de la Cellule à l’Espace.',body}));
for (const n of data.news) {
  const article = `${nav('../',true)}<main id="contenu" class="article wrap"><a class="text-link" href="../#actualites">← Toutes les actualités</a><div class="article-heading"><p class="eyebrow">${esc(n.category)} <span class="separator">/</span> <time datetime="${n.date}">${date(n.date)}</time></p><h1>${esc(n.title)}</h1><p class="article-lead">${esc(n.summary)}</p></div><div class="article-body">${n.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}<aside>SporeMP reste un projet expérimental. Les essais décrits ici ne constituent pas une version publique de la campagne multijoueur.</aside><a class="button ghost" href="../#avenir">Découvrir les prochaines étapes ${arrow}</a></div></main>${footer('../')}`;
  await writeFile(path.join(out,'actualites',n.slug+'.html'),shell({title:n.title+' — SporeMP',description:n.summary,body:article,prefix:'../',canonical:'actualites/'+n.slug+'.html'}));
}
for(const f of ['styles.css','site.js']) await copyFile(path.join(root,f),path.join(out,f));
await copyFile(path.join(root,'assets','universe.png'),path.join(out,'assets','universe.png'));
await writeFile(path.join(out,'.nojekyll'),'');
await writeFile(path.join(out,'404.html'), shell({title:'Page introuvable — SporeMP',description:'Retrouvez le site du projet SporeMP.',prefix:data.siteUrl,body:`${nav(data.siteUrl)}<main id="contenu" class="article wrap"><p class="eyebrow">404 / Hors de la carte</p><h1>Cette planète<br>reste introuvable.</h1><p>Cette page a peut-être changé d’adresse.</p><a class="button primary" href="${esc(data.siteUrl)}">Retour à l’accueil</a></main>${footer(data.siteUrl)}`}));
await writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['',...data.news.map(n=>'actualites/'+n.slug+'.html')].map(p=>`<url><loc>${esc(data.siteUrl+p)}</loc></url>`).join('')}</urlset>`);
console.log(`Built homepage, ${data.news.length} articles, 404, sitemap and assets. Donation link: ${data.leetchiUrl?'configured':'pending'}.`);
