export default {
  lang: 'en', locale: 'en-GB', name: 'English', other: 'Français',
  title: 'SporeMP — A universe worth sharing',
  description: 'An independent multiplayer project for the original SPORE. Follow the journey towards five stages, independent evolution, and one shared universe.',
  nav: { universe: 'The idea', journal: 'Journal', roadmap: 'Roadmap', support: 'Support the project', menu: 'Menu', close: 'Close menu', skip: 'Skip to content', home: 'SporeMP home', language: 'Change language' },
  hero: { eyebrow: 'THE ORIGINAL SPORE. A NEW POSSIBILITY.', first: 'Evolution.', second: 'With company.', body: 'From your first cell to your next galaxy. We’re building a way to share the journey.', primary: 'Discover the project', secondary: 'Follow development', note: 'Independent fan project · In development', alt: 'Two little alien creatures together on a lush planet in a star-filled universe.', caption: 'A little imagination. A much bigger universe.', art: 'Original concept artwork · not gameplay' },
  pulse: { label: 'DEVELOPMENT LOG', text: 'Two locations. One shared world.', link: 'Read the latest breakthrough', detail: 'Creature gameplay is our next focus.' },
  idea: { eyebrow: 'A FAMILIAR WORLD. SOME UNFAMILIAR FACES.', title: 'Your species.\nOur universe.', body: 'SPORE has always been about possibility. SporeMP asks one more question: what if someone else was out there, evolving alongside you?', items: [
    { number: '01', title: 'Still wonderfully SPORE.', text: 'The original game, its strange creatures, its editors, and its native gameplay. The ambition is to bring players together inside the game you know.' },
    { number: '02', title: 'Take your own path.', text: 'Different species. Different places. Different stages of evolution. A shared universe should leave room for everyone’s own story.' },
    { number: '03', title: 'Have somewhere to return to.', text: 'The goal is a persistent world that belongs to the group, with dedicated hosting and progress you can return to after a disconnect.' }
  ], foot: 'That’s the vision. Today’s verified tests cover specific Creature-stage scenarios; the complete campaign is still being built.' },
  stages: { eyebrow: 'THE WHOLE JOURNEY', title: 'Small beginnings.\nShared possibilities.', intro: 'All five original stages are part of the plan. Explore what each one means for the project.', label: 'Original SPORE stages', goal: 'THE AMBITION', statusLabel: 'WHERE IT STANDS', items: [
    { id: 'cell', name: 'Cell', number: '01', title: 'Start small. Dream very, very big.', text: 'Begin at the bottom of the food chain and shape a species of your own, in a universe that other players also call home.', status: 'Planned', detail: 'Cell gameplay investigation comes after the shared-world foundations. Native Cell multiplayer is not yet verified.', mark: 'M12' },
    { id: 'creature', name: 'Creature', number: '02', title: 'A strange new world. A familiar face.', text: 'Explore on your own, cross paths with another creature, and let the original game bring the encounter to life.', status: 'Current focus', detail: 'Shared encounters, saved progress, and travel have passed bounded original-game tests. Work now turns to normal Creature gameplay and progression.', mark: 'M11' },
    { id: 'tribal', name: 'Tribal', number: '03', title: 'A species becomes a community.', text: 'Build a tribe in a world shaped by more than one player. Cooperation, rivalry, and a place to belong are part of the long-term vision.', status: 'Planned', detail: 'Tribal gameplay depends on the earlier stages and faction systems. Its multiplayer implementation is still ahead.', mark: 'M13' },
    { id: 'civilization', name: 'Civilization', number: '04', title: 'Think beyond your own city.', text: 'Grow a civilization and share a planet with other emerging powers, preserving SPORE’s original economy and gameplay.', status: 'Planned', detail: 'Civilization multiplayer requires the preceding stage and faction work. No native multiplayer coverage is claimed yet.', mark: 'M14' },
    { id: 'space', name: 'Space', number: '05', title: 'There’s room for more than one explorer.', text: 'Leave your home world and find other players somewhere among the stars. One persistent galaxy is the destination.', status: 'Planned', detail: 'Space, interactions between stages, and the complete campaign remain future milestones. Galactic Adventures is a separate optional extension.', mark: 'M15–M17' }
  ] },
  journal: { eyebrow: 'NOTES FROM DEVELOPMENT', title: 'One discovery\nat a time.', intro: 'Real progress, open questions, and the work between them.', all: 'All journal entries', read: 'Read the story', back: 'Back to the journal', related: 'Keep exploring', archiveTitle: 'The development journal.', archiveIntro: 'A record of what has been tried, what has worked, and what comes next.', boundary: 'About these results', source: 'Project status & evidence', minutes: 'min read', latest: 'LATEST ENTRY' },
  roadmap: { eyebrow: 'THE ROAD AHEAD', title: 'A universe takes time.', intro: 'We’re building the foundations first, then the full experience. Milestones describe tested work, not a release countdown.', link: 'Explore the full development plan', phases: [
    { status: 'TESTED FOUNDATIONS', title: 'Make a shared world possible.', text: 'Original-game workers, shared encounters, creation checks, saving, recovery, and travel between two prepared Creature locations.', range: 'M00–M10', state: 'done' },
    { status: 'WE ARE HERE', title: 'Bring everyday gameplay to life.', text: 'Creature abilities, social interactions, progression, and then the Cell stage. The familiar things that make a world worth playing.', range: 'M11–M12', state: 'current' },
    { status: 'ON THE HORIZON', title: 'Connect the whole campaign.', text: 'Tribes, civilizations, space, cross-stage consequences, and editors. Independent journeys through all five stages.', range: 'M13–M17', state: 'future' },
    { status: 'THE DESTINATION', title: 'Make it ready for everyone.', text: 'Internet hosting, installation, recovery, and release testing. A complete experience that players can set up and use.', range: 'M18–M19', state: 'future' }
  ], note: 'The tested foundations apply to recorded Creature scenarios. There is no public release date yet.' },
  releases: { eyebrow: 'LAUNCHER NOTES', title: 'The little things matter, too.', intro: 'Selected changes in the development launcher. These version numbers do not indicate a public multiplayer release.', items: [
    { version: '0.1.13', date: '2026-09-27', title: 'The journal catches up with world travel.', text: 'The launcher’s news now covers the tested meetings, return journeys, shared saves, and recovery work.' },
    { version: '0.1.12', date: '2026-09-24', title: 'An invitation to the right place.', text: 'Prepared location invitations select the corresponding Creature scene and check the original save before launch.' },
    { version: '0.1.11', date: '2026-09-22', title: 'A clearer return to your world.', text: 'Rejoin confirms that the experimental shared save has been restored and the scene is ready.' }
  ], full: 'All launcher release notes' },
  faq: { eyebrow: 'BEFORE YOU PACK YOUR SPACESHIP', title: 'A few good questions.', items: [
    { q: 'Can I play it yet?', a: 'SporeMP is an experimental project, not a finished public multiplayer release. The working tests use prepared Creature worlds and developer tools. Follow the journal for progress towards a player-ready version.' },
    { q: 'Is this a new game or a mod?', a: 'A multiplayer project for the original Windows version of SPORE. The goal is to keep its native gameplay, creatures, editors, and progression while adding a shared universe.' },
    { q: 'Will every stage be multiplayer?', a: 'That is the goal: Cell, Creature, Tribal, Civilization, and Space, with independent progression in one persistent universe. The entire campaign is not implemented yet. Galactic Adventures multiplayer is optional future work.' },
    { q: 'When is the release?', a: 'There is no announced release date. Development is guided by actual original-game tests, followed by complete gameplay coverage, usable hosting, and release qualification.' },
    { q: 'How can I help?', a: 'Follow the project, share the development journal, explore the public source, or contribute through the optional Leetchi fundraiser. A donation supports development; it does not purchase access or promise a release date.' }
  ] },
  support: { eyebrow: 'FOR THE LOVE OF A VERY STRANGE GAME', title: 'Help this little\nuniverse grow.', text: 'Follow along, tell a fellow SPORE fan, or support development. Every bit of interest helps the project find its people.', primary: 'Support on Leetchi', secondary: 'Explore the source', note: 'Entirely optional. No paid access or promised release date.' },
  footer: { tagline: 'A universe worth sharing.', legal: 'An independent fan project. Not affiliated with or endorsed by EA or Maxis. SPORE belongs to its respective rights holders.', art: 'Original AI-assisted concept artwork; not a gameplay capture.', copyright: 'SporeMP · 2026', top: 'Back to the stars', source: 'Public source', journal: 'Development journal', credits: 'Asset credits' },
  notFound: { eyebrow: 'UNCHARTED TERRITORY', title: 'A little too far\nfrom home.', text: 'This corner of the universe doesn’t have a page. Let’s get you back to somewhere familiar.', link: 'Back to SporeMP' },
  news: [
    { slug: 'creature-gameplay-next', date: '2026-09-27', category: 'What’s next', title: 'Back to being a creature.', summary: 'The shared-world foundations are in place. Now the focus moves to the everyday life of a Creature-stage player.', milestone: 'M11 · IN PROGRESS', paragraphs: [
      'A shared world needs more than travel and a successful connection. It needs the things you actually do in SPORE: meeting a species, using an ability, earning progress, and carrying that progress into the next encounter.',
      'The next milestone maps out normal Creature gameplay and the original game functions behind it. The first increment adds a coverage audit and tooling to examine the game’s social-reward path.',
      'Those new tools have passed host and fixture checks. The new original-game social interaction tests have not run yet. They are the next step towards broader Creature coverage, followed by an independent investigation of the Cell stage.'
    ], boundary: 'M11 is in progress. The new audit and trace tooling are not native gameplay acceptance. Earlier Creature foundations remain qualified only within their recorded scenarios.' },
    { slug: 'explore-apart-meet-again', date: '2026-09-26', category: 'Shared universe', title: 'Two places. One universe.', summary: 'Separate locations, a meeting, a journey home, and a return after restarting the world.', milestone: 'M10 · VERIFIED FOUNDATION', paragraphs: [
      'The latest original-game tests put two prepared Creature locations in the same universe. Each location continued its own simulation. A player travelled to the other location, interacted there, and returned with the current state intact.',
      'The tests also saved both locations, published the shared checkpoint, restarted the world, and reconnected the players. A recorded set of 36 worker-fault cases explored interruptions around travel and cleanup, with recovery checked in the original game.',
      'This is a foundation for players taking independent paths and meeting again. The next work is normal Creature gameplay coverage. Travel still relies on development tools; this is not the public hosting experience.'
    ], boundary: 'Verified for the pinned original Creature locations and the recorded transfer and recovery scenarios. Arbitrary worlds and the complete campaign are not qualified.' },
    { slug: 'a-shared-world-worth-returning-to', date: '2026-09-22', category: 'Persistence', title: 'Progress that survives a restart.', summary: 'The experimental world can restore both players, their tested progress, and the ownership of a creation.', milestone: 'M09 · VERIFIED FOUNDATION', paragraphs: [
      'A shared world matters more when you can come back to it. In the prepared Creature world, original SPORE saves and reloads both players and their existing actors, including the inventory and progression recorded by the tests.',
      'Recovery trials interrupted the save and publication process at specific points. The selected checkpoint remained complete, and resubmitting a recorded reward did not grant it a second time.',
      'Both original clients then reconnected to the same universe. Recovery currently uses an explicit protected workflow; unattended hosting and arbitrary campaign saves still need their own qualification.'
    ], boundary: 'These results apply to the pinned two-player Creature checkpoint. They do not establish automatic hosting, universal save compatibility, or a finished persistence system for every stage.' },
    { slug: 'creations-without-interrupting-play', date: '2026-09-22', category: 'Creation', title: 'Room to make something strange.', summary: 'Original editor and content tests lay the groundwork for bringing creations into a shared world.', milestone: 'M08 · VERIFIED FOUNDATION', paragraphs: [
      'Creating something wonderfully odd is central to SPORE. This milestone tested the original Creature editor’s save and import path, matching the recorded parts and capabilities before a creation could be approved.',
      'The tests checked missing parts and mismatched terrain, exercised concurrent editing and cancellation, and produced two immutable publications validated by the original game.',
      'These checks establish a content foundation. They do not yet let players replace a live campaign avatar freely, and the approval process remains a developer workflow.'
    ], boundary: 'Verified for the recorded Creature content and editor foundation. Full native editors and campaign-wide creation use remain later work.' },
    { slug: 'shared-encounter-verified', date: '2026-09-21', category: 'Encounters', title: 'An encounter with one shared outcome.', summary: 'Combat, feeding, reconnects, and an interrupted connection all have to agree on what happened.', milestone: 'M07 · VERIFIED FOUNDATION', paragraphs: [
      'Two connected creatures need to agree on more than their positions. The recorded shared encounter tested original combat and contested feeding, including who could act and which outcome each player received.',
      'Later runs introduced actual packet delay and loss. Reconnecting preserved the recorded result, late actions were refused where required, and a fresh-session reset was checked through original movement and jumping.',
      'These trials give the project a tested encounter foundation. Broader ability, scene, and campaign coverage is still ahead.'
    ], boundary: 'The encounter is verified only for the pinned living Creature scenario, including its declared impaired-network and reset cases.' },
    { slug: 'first-shared-scene', date: '2026-09-15', category: 'Networking', title: 'Two players step into the same scene.', summary: 'Distinct original-game actors move, jump, disconnect, and find their way back into a shared scene.', milestone: 'M06 · VERIFIED FOUNDATION', paragraphs: [
      'The networking foundation connects an original-game worker and two original clients. Each player controls a distinct actor in the prepared Creature scene.',
      'Recorded trials cover original movement and jumping, fresh scene state after reconnecting, and refusal of incompatible protocol messages. Join and Rejoin in the Windows launcher preserve the same player identity.',
      'This establishes a real shared scene. A complete Internet setup flow, broader gameplay, and release packaging remain future work.'
    ], boundary: 'Verified for the recorded living Creature scene. Two test clients do not establish a capacity promise or complete Internet hosting support.' },
    { slug: 'rewards-counted-once', date: '2026-09-14', category: 'Gameplay', title: 'The same result. No extra reward.', summary: 'A shared scene needs a single source of truth for actions and their consequences.', milestone: 'M05 · VERIFIED FOUNDATION', paragraphs: [
      'The authority and replica tests check that a native result reaches clients without awarding the same reward twice. Clients send intentions, while the original-game authority resolves the recorded action.',
      'The prepared Creature trials challenged local mutations, disconnected clients, and exercised publication boundaries. Additional checks covered active-action cleanup and saved-world load refusal.',
      'This is part of keeping the original gameplay consistent between players. It is bounded evidence for the tested scene and abilities, rather than complete campaign protection.'
    ], boundary: 'Verified only for the recorded living Creature scenario and its specific mutation, reward, and disconnect checks.' },
    { slug: 'world-beyond-the-player', date: '2026-09-13', category: 'Dedicated world', title: 'A world with a life of its own.', summary: 'The original game can keep an experimental world moving after the human client and launcher close.', milestone: 'M04 · VERIFIED FOUNDATION', paragraphs: [
      'A shared universe should not depend on one player leaving their session open. The worker tests run original SPORE as the authority for a prepared Creature world.',
      'Recorded trials checked unattended native actions, overlapping isolated workers, crash containment, clean shutdown, and recovery from a sealed checkpoint. The human client and launcher could close without becoming the authority.',
      'These are rendered original-game workers with recorded desktop and stall limits. Usable dedicated Internet hosting remains a later milestone.'
    ], boundary: 'Qualified for the recorded rendered Creature worker setup. No headless mode or general hosting capacity is claimed.' }
  ]
};
