export default {
  lang: 'fr', locale: 'fr-FR', name: 'Français', other: 'English',
  title: 'SporeMP — Un univers à partager',
  description: 'Un projet multijoueur indépendant pour le SPORE original. Suivez sa création : cinq phases, des évolutions indépendantes et un univers partagé.',
  nav: { universe: 'Le projet', journal: 'Journal', roadmap: 'La suite', support: 'Soutenir le projet', menu: 'Menu', close: 'Fermer le menu', skip: 'Aller au contenu', home: 'Accueil SporeMP', language: 'Changer de langue' },
  hero: { eyebrow: 'LE SPORE ORIGINAL. UNE NOUVELLE POSSIBILITÉ.', first: 'Évoluer.', second: 'Ensemble.', body: 'De votre première cellule à votre prochaine galaxie. Nous créons une façon de partager l’aventure.', primary: 'Découvrir le projet', secondary: 'Suivre le développement', note: 'Projet de fans indépendant · En développement', alt: 'Deux petites créatures extraterrestres réunies sur une planète verdoyante dans un univers étoilé.', caption: 'Un peu d’imagination. Un univers bien plus grand.', art: 'Illustration originale · pas une capture du jeu' },
  pulse: { label: 'CARNET DE BORD', text: 'Deux lieux. Un même univers.', link: 'Découvrir cette avancée', detail: 'Prochaine étape : le quotidien des créatures.' },
  idea: { eyebrow: 'UN MONDE FAMILIER. DE NOUVELLES RENCONTRES.', title: 'Votre espèce.\nNotre univers.', body: 'SPORE a toujours ouvert le champ des possibles. SporeMP pose une question de plus : et si quelqu’un évoluait là-bas, à vos côtés ?', items: [
    { number: '01', title: 'Toujours aussi SPORE.', text: 'Le jeu original, ses étranges créatures, ses éditeurs et ses mécaniques. L’ambition est de réunir les joueurs dans le jeu qu’ils connaissent.' },
    { number: '02', title: 'À chacun son chemin.', text: 'Des espèces, des lieux et des phases d’évolution différents. Un univers partagé doit laisser à chacun la place d’écrire sa propre histoire.' },
    { number: '03', title: 'Un monde à retrouver.', text: 'L’objectif : un monde persistant pour le groupe, un hébergement dédié et une progression que l’on retrouve après une déconnexion.' }
  ], foot: 'Voilà la vision. Les tests vérifiés concernent aujourd’hui des scénarios précis de la phase Créature ; la campagne complète reste en développement.' },
  stages: { eyebrow: 'TOUTE L’AVENTURE', title: 'Petits débuts.\nGrandes rencontres.', intro: 'Les cinq phases originales font partie du projet. Découvrez leur place dans cet univers.', label: 'Phases du SPORE original', goal: 'L’AMBITION', statusLabel: 'OÙ EN EST-ON ?', items: [
    { id: 'cell', name: 'Cellule', number: '01', title: 'Commencer petit. Voir très, très grand.', text: 'Partir du bas de la chaîne alimentaire et façonner sa propre espèce, dans un univers que d’autres joueurs habitent aussi.', status: 'Prévu', detail: 'L’étude du gameplay Cellule suivra les fondations du monde partagé. Son multijoueur natif n’est pas encore vérifié.', mark: 'M12' },
    { id: 'creature', name: 'Créature', number: '02', title: 'Un monde étrange. Un visage familier.', text: 'Explorer à son rythme, croiser une autre créature et laisser le jeu original donner vie à cette rencontre.', status: 'Priorité actuelle', detail: 'Rencontres, sauvegarde et voyages ont passé des tests ciblés dans le jeu original. Le travail porte maintenant sur le gameplay et la progression habituels.', mark: 'M11' },
    { id: 'tribal', name: 'Tribu', number: '03', title: 'Une espèce devient une communauté.', text: 'Fonder une tribu dans un monde façonné par plusieurs joueurs. Coopération, rivalités et sentiment d’appartenance font partie de la vision.', status: 'Prévu', detail: 'La phase Tribu dépend des phases précédentes et des systèmes de factions. Sa réalisation multijoueur reste à venir.', mark: 'M13' },
    { id: 'civilization', name: 'Civilisation', number: '04', title: 'Penser au-delà de sa propre ville.', text: 'Développer une civilisation et partager une planète avec d’autres puissances, en conservant l’économie et les mécaniques de SPORE.', status: 'Prévu', detail: 'Le multijoueur de la phase Civilisation nécessite les travaux précédents sur les phases et les factions. Il n’est pas encore vérifié dans le jeu.', mark: 'M14' },
    { id: 'space', name: 'Espace', number: '05', title: 'Il y a de la place pour plusieurs explorateurs.', text: 'Quitter sa planète et retrouver d’autres joueurs quelque part parmi les étoiles. Une galaxie persistante : voilà la destination.', status: 'Prévu', detail: 'L’Espace, les interactions entre phases et la campagne complète restent à réaliser. Aventures Galactiques est une extension optionnelle distincte.', mark: 'M15–M17' }
  ] },
  journal: { eyebrow: 'LE CARNET DU PROJET', title: 'Une découverte\naprès l’autre.', intro: 'Les avancées, les questions ouvertes et le travail pour y répondre.', all: 'Tout le journal', read: 'Lire l’article', back: 'Retour au journal', related: 'Continuer l’exploration', archiveTitle: 'Le journal du développement.', archiveIntro: 'Ce qui a été tenté, ce qui a fonctionné et ce qui nous attend.', boundary: 'La portée de ces résultats', source: 'État du projet et preuves', minutes: 'min de lecture', latest: 'DERNIER ARTICLE' },
  roadmap: { eyebrow: 'LE CHEMIN À PARCOURIR', title: 'Un univers prend du temps.', intro: 'D’abord les fondations, puis l’expérience complète. Les jalons décrivent un travail testé, pas un compte à rebours.', link: 'Consulter le plan de développement complet', phases: [
    { status: 'FONDATIONS TESTÉES', title: 'Rendre le monde partagé possible.', text: 'Simulation originale, rencontres, vérification des créations, sauvegarde, récupération et voyages entre deux lieux Créature préparés.', range: 'M00–M10', state: 'done' },
    { status: 'NOUS EN SOMMES LÀ', title: 'Faire vivre le quotidien du jeu.', text: 'Capacités, interactions sociales et progression en phase Créature, puis phase Cellule. Tout ce qui donne envie d’habiter ce monde.', range: 'M11–M12', state: 'current' },
    { status: 'À L’HORIZON', title: 'Relier toute la campagne.', text: 'Tribus, civilisations, espace, conséquences entre phases et éditeurs. Des parcours indépendants à travers les cinq phases.', range: 'M13–M17', state: 'future' },
    { status: 'LA DESTINATION', title: 'Le rendre accessible à tous.', text: 'Hébergement Internet, installation, récupération et tests de sortie. Une expérience que les joueurs peuvent installer et utiliser.', range: 'M18–M19', state: 'future' }
  ], note: 'Les fondations testées concernent des scénarios Créature documentés. Aucune date de sortie publique n’est annoncée.' },
  releases: { eyebrow: 'DU CÔTÉ DU LANCEUR', title: 'Les petits détails comptent aussi.', intro: 'Une sélection des évolutions du lanceur de développement. Ces versions ne désignent pas une sortie publique du multijoueur.', items: [
    { version: '0.1.14', date: '2026-09-27', title: 'La progression sociale retrouve son propriétaire.', text: 'Le journal présente les récompenses sociales testées, le tutoriel Premier ADN personnel et la progression restaurée. La phase Créature complète reste en développement.' },
    { version: '0.1.13', date: '2026-09-27', title: 'Le journal raconte les voyages.', text: 'Les actualités du lanceur présentent les rencontres, les retours, les sauvegardes partagées et les essais de récupération.' },
    { version: '0.1.12', date: '2026-09-24', title: 'Une invitation au bon endroit.', text: 'Les invitations préparées sélectionnent le lieu Créature correspondant et vérifient la sauvegarde originale avant le lancement.' },
  ], full: 'Toutes les notes du lanceur' },
  faq: { eyebrow: 'AVANT DE PRÉPARER VOTRE VAISSEAU', title: 'Quelques bonnes questions.', items: [
    { q: 'Est-ce que je peux déjà y jouer ?', a: 'SporeMP est un projet expérimental, pas un multijoueur public terminé. Les essais utilisent des mondes Créature préparés et des outils de développement. Le journal raconte le chemin vers une version prête pour les joueurs.' },
    { q: 'C’est un nouveau jeu ou un mod ?', a: 'Un projet multijoueur pour la version Windows du SPORE original. L’objectif est de conserver ses mécaniques, ses créatures, ses éditeurs et sa progression tout en ajoutant un univers partagé.' },
    { q: 'Toutes les phases seront-elles multijoueurs ?', a: 'C’est le but : Cellule, Créature, Tribu, Civilisation et Espace, avec une progression indépendante dans un même univers persistant. Toute la campagne n’est pas encore réalisée. Aventures Galactiques reste un prolongement optionnel.' },
    { q: 'Quand est prévue la sortie ?', a: 'Aucune date n’est annoncée. Le développement avance au rythme des tests dans le jeu original, puis de la couverture du gameplay, de l’hébergement utilisable et de la validation de la sortie.' },
    { q: 'Comment aider le projet ?', a: 'Vous pouvez suivre le projet, partager le journal, consulter le code public ou participer à la cagnotte Leetchi. Un don soutient le développement ; il n’achète pas un accès et ne garantit pas une date de sortie.' }
  ] },
  support: { eyebrow: 'POUR L’AMOUR D’UN JEU VRAIMENT À PART', title: 'Aidons ce petit\nunivers à grandir.', text: 'Suivez l’aventure, parlez-en à un fan de SPORE ou soutenez le développement. Chaque marque d’intérêt aide le projet à trouver son public.', primary: 'Soutenir sur Leetchi', secondary: 'Explorer le code', note: 'Entièrement facultatif. Aucun accès payant ni date de sortie promise.' },
  footer: { tagline: 'Un univers à partager.', legal: 'Un projet de fans indépendant, sans affiliation ni approbation d’EA ou de Maxis. SPORE appartient à ses ayants droit.', art: 'Illustration originale créée avec l’IA ; pas une capture du jeu.', copyright: 'SporeMP · 2026', top: 'Retour aux étoiles', source: 'Code public', journal: 'Journal du développement', credits: 'Crédits des ressources' },
  notFound: { eyebrow: 'TERRITOIRE INCONNU', title: 'Un peu trop loin\nde la maison.', text: 'Ce coin de l’univers n’a pas de page. Retrouvons un endroit plus familier.', link: 'Retour à SporeMP' },
  news: [
    { slug: 'social-rewards-and-saved-progress', date: '2026-09-27', category: 'Essais Créature', title: 'Une récompense sociale au bon joueur.', summary: 'De nouveaux essais dans le jeu original attribuent les récompenses sociales testées et le tutoriel Premier ADN à leur propriétaire, puis restaurent la progression gagnée.', milestone: 'M11 · EN COURS', paragraphs: [
      'Dans le monde Créature préparé, le second joueur gagne désormais la récompense du jeu original après une interaction sociale réussie. Son tutoriel Premier ADN apparaît sur son propre client pendant que l’autre joueur continue à jouer. Sa validation et la progression gagnée sont conservées après une sauvegarde et un rechargement dans le jeu original.',
      'Un nouvel essai a révélé un problème distinct : terminer l’objectif d’espèce donnait encore sa récompense supplémentaire au premier joueur. La correction suit le changement de relation original jusque dans ce traitement différé. Lors de l’essai documenté, le second joueur a reçu 10 ADN pour l’interaction et 25 pour l’objectif ; le solde du premier joueur est resté inchangé.',
      'Un nouveau chargement dans le jeu original a restauré les soldes testés sans attribuer les récompenses une seconde fois. Ce sont des étapes vers le gameplay Créature habituel. Les commandes sociales utilisent encore des outils de développement ; les espèces distinctes, les objectifs indépendants et les autres exigences Créature restent à réaliser et à tester.'
    ], boundary: 'Essais limités au monde Créature préparé, avec une espèce partagée, une meute vide et un seul échange social à la fois. La correction de l’objectif et sa sauvegarde ont été testées localement. M11 et une version multijoueur prête pour le public restent inachevés.' },
    { slug: 'creature-gameplay-next', date: '2026-09-27', category: 'La suite', title: 'Retour à la vie de créature.', summary: 'Les fondations du monde partagé sont là. Place maintenant au quotidien d’un joueur en phase Créature.', milestone: 'M11 · EN COURS', paragraphs: [
      'Un monde partagé a besoin de plus qu’un voyage réussi ou une connexion. Il doit accueillir ce que l’on fait dans SPORE : rencontrer une espèce, utiliser une capacité, progresser et retrouver cette progression à la rencontre suivante.',
      'Le prochain jalon recense le gameplay habituel de la phase Créature et les fonctions du jeu original qui le réalisent. Le premier incrément apporte un audit de couverture et un outil d’analyse des récompenses sociales.',
      'Ces outils ont passé leurs vérifications sur l’hôte et les jeux de données de test. Les nouveaux essais d’interactions sociales dans le jeu original n’ont pas encore eu lieu. Ils prépareront une couverture Créature plus large, puis une étude indépendante de la phase Cellule.'
    ], boundary: 'M11 est en cours. L’audit et les outils d’analyse ne constituent pas une validation du gameplay natif. Les fondations précédentes restent limitées à leurs scénarios documentés.' },
    { slug: 'explore-apart-meet-again', date: '2026-09-26', category: 'Univers partagé', title: 'Deux lieux. Un même univers.', summary: 'Des lieux séparés, une rencontre, un retour chez soi et des retrouvailles après le redémarrage du monde.', milestone: 'M10 · FONDATION VÉRIFIÉE', paragraphs: [
      'Les derniers tests réunissent deux lieux Créature préparés dans un même univers. Chaque lieu poursuit sa propre simulation. Un joueur rejoint l’autre lieu, y agit, puis revient avec son état actuel préservé.',
      'Les essais sauvegardent également les deux lieux, publient leur état partagé, redémarrent le monde et reconnectent les joueurs. Une série documentée de 36 interruptions de processus explore les échecs autour du voyage et de sa finalisation, avec récupération vérifiée dans le jeu original.',
      'C’est une base pour suivre des chemins indépendants et se retrouver. La prochaine étape porte sur le gameplay Créature habituel. Les voyages utilisent encore des outils de développement ; ce n’est pas encore l’hébergement destiné au public.'
    ], boundary: 'Vérifié pour les lieux Créature originaux préparés et les scénarios de transfert et de récupération documentés. Les mondes arbitraires et la campagne complète ne sont pas validés.' },
    { slug: 'a-shared-world-worth-returning-to', date: '2026-09-22', category: 'Persistance', title: 'Une progression qui survit au redémarrage.', summary: 'Le monde expérimental restaure les deux joueurs, la progression testée et la propriété d’une création.', milestone: 'M09 · FONDATION VÉRIFIÉE', paragraphs: [
      'Un monde partagé prend tout son sens quand on peut le retrouver. Dans le monde Créature préparé, le SPORE original sauvegarde et recharge les deux joueurs et leurs créatures existantes, avec l’inventaire et la progression suivis pendant les tests.',
      'Les essais interrompent la sauvegarde et la publication à des moments précis. Le point de reprise retenu reste complet et une récompense déjà enregistrée n’est pas attribuée une seconde fois.',
      'Les deux clients originaux se reconnectent ensuite au même univers. La récupération utilise encore une procédure protégée explicite ; l’hébergement autonome et les sauvegardes arbitraires doivent être vérifiés séparément.'
    ], boundary: 'Ces résultats concernent le point de reprise Créature à deux joueurs préparé. Ils ne valident pas un hébergement automatique ou une compatibilité universelle des sauvegardes.' },
    { slug: 'creations-without-interrupting-play', date: '2026-09-22', category: 'Création', title: 'De la place pour les idées bizarres.', summary: 'Les essais de l’éditeur original préparent l’arrivée des créations dans un monde partagé.', milestone: 'M08 · FONDATION VÉRIFIÉE', paragraphs: [
      'Créer quelque chose d’étrange fait partie de l’âme de SPORE. Ce jalon teste la sauvegarde et l’importation dans l’éditeur Créature original, en vérifiant les éléments et les capacités avant approbation.',
      'Les essais contrôlent les éléments manquants et les terrains incompatibles, couvrent l’édition simultanée et son annulation, puis produisent deux publications immuables validées par le jeu original.',
      'Ces contrôles posent les fondations du contenu partagé. Ils ne permettent pas encore de remplacer librement une créature de campagne en cours ; l’approbation reste une procédure de développement.'
    ], boundary: 'Vérifié pour la base de contenu et d’édition Créature documentée. Les éditeurs complets et leur utilisation dans toute la campagne restent à venir.' },
    { slug: 'shared-encounter-verified', date: '2026-09-21', category: 'Rencontres', title: 'Une rencontre, un résultat partagé.', summary: 'Combat, nourriture, reconnexions : tous doivent s’accorder sur ce qui s’est réellement passé.', milestone: 'M07 · FONDATION VÉRIFIÉE', paragraphs: [
      'Deux créatures connectées doivent partager plus que leur position. La rencontre documentée teste le combat original et la nourriture disputée, notamment qui peut agir et quel résultat revient à chaque joueur.',
      'Les essais suivants introduisent de vrais délais et pertes de paquets. La reconnexion préserve le résultat, certaines actions tardives sont refusées et une remise à zéro déclarée est contrôlée par les déplacements et sauts originaux.',
      'Ces essais forment une base de rencontre vérifiée. La couverture des autres capacités, scènes et situations de campagne reste à développer.'
    ], boundary: 'La rencontre est vérifiée uniquement pour le scénario Créature vivant préparé, avec ses cas déclarés de réseau dégradé et de remise à zéro.' },
    { slug: 'first-shared-scene', date: '2026-09-15', category: 'Réseau', title: 'Deux joueurs dans la même scène.', summary: 'Deux créatures originales se déplacent, sautent, se déconnectent et retrouvent la scène partagée.', milestone: 'M06 · FONDATION VÉRIFIÉE', paragraphs: [
      'La base réseau relie un processus original chargé de la simulation et deux clients originaux. Chaque joueur contrôle une créature distincte dans la scène Créature préparée.',
      'Les essais couvrent déplacements, sauts, état de scène actualisé après reconnexion et refus des messages incompatibles. Les fonctions Rejoindre et Rejoindre à nouveau du lanceur Windows préservent l’identité du joueur.',
      'Il s’agit d’une véritable scène partagée. La configuration Internet complète, le gameplay plus large et la préparation de la sortie restent à venir.'
    ], boundary: 'Vérifié pour la scène Créature vivante documentée. Deux clients de test ne constituent ni une promesse de capacité ni une validation de l’hébergement Internet complet.' },
    { slug: 'rewards-counted-once', date: '2026-09-14', category: 'Gameplay', title: 'Le même résultat. Sans double récompense.', summary: 'Une scène partagée a besoin d’une seule référence pour les actions et leurs conséquences.', milestone: 'M05 · FONDATION VÉRIFIÉE', paragraphs: [
      'Les essais d’autorité et de réplication vérifient qu’un résultat natif atteint les clients sans attribuer deux fois la même récompense. Les clients transmettent leurs intentions ; le jeu original faisant autorité résout l’action testée.',
      'Les scénarios Créature préparés mettent à l’épreuve les modifications locales, les déconnexions et les limites de publication. D’autres contrôles couvrent l’arrêt d’actions actives et le refus de chargements incompatibles.',
      'Ces travaux contribuent à la cohérence du gameplay entre joueurs. Leur portée reste celle de la scène et des capacités testées, pas une protection de toute la campagne.'
    ], boundary: 'Vérifié uniquement pour le scénario Créature vivant documenté et ses contrôles précis de modifications, récompenses et déconnexions.' },
    { slug: 'world-beyond-the-player', date: '2026-09-13', category: 'Monde dédié', title: 'Un monde qui vit sa propre vie.', summary: 'Le jeu original peut continuer à simuler un monde expérimental après la fermeture du client humain et du lanceur.', milestone: 'M04 · FONDATION VÉRIFIÉE', paragraphs: [
      'Un univers partagé ne devrait pas dépendre d’un joueur qui garde sa partie ouverte. Les essais utilisent des processus SPORE originaux comme autorité d’un monde Créature préparé.',
      'Ils vérifient les actions sans intervention, les processus isolés simultanés, le confinement des plantages, l’arrêt propre et la reprise depuis une sauvegarde scellée. Le client humain et le lanceur peuvent fermer sans devenir l’autorité du monde.',
      'Ces processus originaux restent affichés et soumis aux limites de bureau et de blocage documentées. Un hébergement Internet dédié utilisable est un jalon ultérieur.'
    ], boundary: 'Validé pour l’environnement Créature avec rendu documenté. Aucun mode sans affichage ni aucune capacité générale d’hébergement ne sont annoncés.' }
  ]
};
