const esc = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const lines = value => esc(value).replaceAll('\n', '<br>');
const arrow = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const external = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M6 18 18 6M6 6h12v12" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const plus = '<span class="faq-plus" aria-hidden="true">+</span>';
const logo = '<span class="wordmark">spore<span class="wordmark-mp">mp</span><span class="logo-orbit" aria-hidden="true"></span></span>';
const source = 'https://github.com/raph559/SporeMP';

export function render(c, config, manifest, kind = 'home', article) {
  const prefix = c.lang === 'fr' ? 'fr/' : '';
  const route = kind === 'article' ? `news/${article.slug}.html` : kind === 'archive' ? 'news/' : kind === '404' ? '404.html' : '';
  const file = `${prefix}${route}`;
  const depth = file.split('/').filter(Boolean).length - (file.endsWith('/') || !file ? 0 : 1);
  const root = kind === '404' ? config.siteUrl : '../'.repeat(depth);
  const home = `${root}${prefix}` || './';
  const alternate = `${root}${c.lang === 'en' ? 'fr/' : ''}${route}` || './';
  const asset = key => root + manifest[key];
  const date = value => new Intl.DateTimeFormat(c.locale, { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' }).format(new Date(value + 'T12:00:00Z'));
  const newsUrl = slug => `${home}news/${slug}.html`;
  const journalUrl = `${home}news/`;
  const title = kind === 'article' ? `${article.title} — SporeMP` : kind === 'archive' ? `${c.journal.archiveTitle} — SporeMP` : kind === '404' ? `404 — SporeMP` : c.title;
  const description = kind === 'article' ? article.summary : c.description;
  const canonical = new URL(file, config.siteUrl).href;
  const sectionLink = (id, label) => `<a href="${home}#${id}" data-nav="${id}">${esc(label)}</a>`;
  const eyebrow = text => `<p class="eyebrow">${esc(text)}</p>`;
  const link = (url, text, cls = 'text-link', out = false) => `<a class="${cls}" href="${esc(url)}"${out ? ' target="_blank" rel="noopener noreferrer"' : ''}>${esc(text)}${out ? external : arrow}</a>`;
  const header = `<header class="site-header"><div class="header-inner wrap"><a class="brand" href="${home}" aria-label="${esc(c.nav.home)}">${logo}</a><nav class="desktop-nav" aria-label="${esc(c.nav.menu)}">${sectionLink('universe', c.nav.universe)}${sectionLink('journal', c.nav.journal)}${sectionLink('roadmap', c.nav.roadmap)}</nav><div class="header-actions"><a class="language" href="${alternate}" data-language hreflang="${c.lang === 'en' ? 'fr' : 'en'}" aria-label="${esc(c.nav.language)}: ${esc(c.other)}"><span${c.lang === 'en' ? ' class="selected"' : ''}>EN</span><span class="language-divider">/</span><span${c.lang === 'fr' ? ' class="selected"' : ''}>FR</span></a><a class="header-support" href="${home}#support">${esc(c.nav.support)}${external}</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-navigation"><span>${esc(c.nav.menu)}</span><span class="menu-lines" aria-hidden="true"></span></button></div></div><nav class="mobile-nav wrap" id="mobile-navigation" aria-label="${esc(c.nav.menu)}">${sectionLink('universe', c.nav.universe)}${sectionLink('journal', c.nav.journal)}${sectionLink('roadmap', c.nav.roadmap)}${sectionLink('support', c.nav.support)}</nav></header>`;
  const footer = `<footer class="site-footer"><div class="wrap"><div class="footer-main"><div><a class="brand" href="${home}" aria-label="${esc(c.nav.home)}">${logo}</a><p class="footer-tagline">${esc(c.footer.tagline)}</p></div><div class="footer-links">${link(journalUrl, c.footer.journal)}${link(source, c.footer.source, 'text-link', true)}${link('#top', c.footer.top)}</div></div><div class="footer-bottom"><p>${esc(c.footer.legal)}<br>${esc(c.footer.art)} <a href="${root}assets/credits.txt">${esc(c.footer.credits)}</a></p><span>${esc(c.footer.copyright)}</span></div></div></footer>`;
  const newsRow = (n, index) => `<article class="news-row"><span class="news-number" aria-hidden="true">${String(index + 1).padStart(2, '0')}</span><div class="news-meta"><span>${esc(n.category)}</span><time datetime="${n.date}">${date(n.date)}</time></div><div class="news-row-body"><h3><a href="${newsUrl(n.slug)}">${esc(n.title)}<span class="row-hit" aria-hidden="true"></span></a></h3><p>${esc(n.summary)}</p></div><span class="row-arrow" aria-hidden="true">${arrow}</span></article>`;
  let main = '';
  if (kind === 'home') {
    main = `<section class="hero"><div class="hero-art"><img src="${asset('planet')}" alt="${esc(c.hero.alt)}" width="1536" height="1024" fetchpriority="high"></div><div class="hero-inner wrap"><div class="hero-copy">${eyebrow(c.hero.eyebrow)}<h1>${esc(c.hero.first)}<br><span>${esc(c.hero.second)}</span></h1><p class="hero-description">${esc(c.hero.body)}</p><div class="hero-actions">${link('#universe', c.hero.primary, 'button button-light')}${link('#journal', c.hero.secondary, 'hero-secondary')}</div><p class="hero-note"><span class="asterisk" aria-hidden="true">✳</span>${esc(c.hero.note)}</p></div><div class="art-caption"><span>${esc(c.hero.caption)}</span><small>${esc(c.hero.art)}</small></div></div></section>
    <aside class="development-pulse"><div class="wrap pulse-inner"><span class="pulse-label">${esc(c.pulse.label)}</span><a href="${newsUrl('explore-apart-meet-again')}">${esc(c.pulse.text)}${arrow}</a><span class="pulse-detail">${esc(c.pulse.detail)}</span></div></aside>
    <section class="section idea wrap" id="universe"><div class="section-heading idea-heading"><div>${eyebrow(c.idea.eyebrow)}<h2>${lines(c.idea.title)}</h2></div><p class="section-intro">${esc(c.idea.body)}</p></div><div class="principles">${c.idea.items.map(i => `<article><span class="principle-number">${i.number}</span><h3>${esc(i.title)}</h3><p>${esc(i.text)}</p></article>`).join('')}</div><p class="scope-note">${esc(c.idea.foot)}</p></section>
    <section class="stages-section section" id="stages"><div class="wrap"><div class="section-heading"><div>${eyebrow(c.stages.eyebrow)}<h2>${lines(c.stages.title)}</h2></div><p class="section-intro">${esc(c.stages.intro)}</p></div><div class="stage-tabs" role="tablist" aria-label="${esc(c.stages.label)}">${c.stages.items.map((s, i) => `<a id="tab-${s.id}" role="tab" aria-selected="${i === 1}" aria-controls="stage-${s.id}" href="#stage-${s.id}"${i !== 1 ? ' tabindex="-1"' : ''}><span class="stage-preview" aria-hidden="true"><img src="${asset('stages')}" width="2048" height="683" alt="" loading="lazy" decoding="async" style="left:${-i * 100}%"></span><span class="stage-tab-label"><span class="stage-number">${s.number}</span><span>${esc(s.name)}</span>${i === 1 ? '<span class="stage-current-dot" aria-hidden="true"></span>' : ''}</span></a>`).join('')}</div><div class="stage-panels">${c.stages.items.map((s, i) => `<section class="stage-panel" id="stage-${s.id}" role="tabpanel" aria-labelledby="tab-${s.id}" tabindex="0" data-initial="${i === 1}"><div class="stage-dream"><span class="eyebrow">${esc(c.stages.goal)}</span><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p></div><div class="stage-reality"><span class="eyebrow">${esc(c.stages.statusLabel)}</span><span class="status-tag${i === 1 ? ' active' : ''}">${esc(s.status)}</span><p>${esc(s.detail)}</p><span class="milestone-ref">${s.mark}</span></div></section>`).join('')}</div><p class="stage-art-note">${esc(c.hero.art)}</p></div></section>
    <section class="section journal wrap" id="journal"><div class="section-heading"><div>${eyebrow(c.journal.eyebrow)}<h2>${lines(c.journal.title)}</h2></div><div class="heading-side"><p>${esc(c.journal.intro)}</p>${link(journalUrl, c.journal.all)}</div></div><div class="news-list">${c.news.slice(0, 3).map(newsRow).join('')}</div></section>
    <section class="roadmap-section section" id="roadmap"><div class="wrap"><div class="section-heading"><div>${eyebrow(c.roadmap.eyebrow)}<h2>${esc(c.roadmap.title)}</h2></div><p class="section-intro">${esc(c.roadmap.intro)}</p></div><div class="roadmap-list">${c.roadmap.phases.map((p, i) => `<article class="roadmap-phase ${p.state}"><div class="phase-track"><span>${p.state === 'done' ? '✓' : String(i + 1).padStart(2, '0')}</span></div><div class="phase-label"><span class="eyebrow">${esc(p.status)}</span><span class="milestone-ref">${p.range}</span></div><div class="phase-copy"><h3>${esc(p.title)}</h3><p>${esc(p.text)}</p></div></article>`).join('')}</div><div class="roadmap-bottom"><p>${esc(c.roadmap.note)}</p>${link(source + '/blob/main/MILESTONES.md', c.roadmap.link, 'text-link', true)}</div></div></section>
    <section class="section releases wrap" id="updates"><div class="section-heading compact"><div>${eyebrow(c.releases.eyebrow)}<h2>${esc(c.releases.title)}</h2></div><p class="section-intro">${esc(c.releases.intro)}</p></div><div class="release-list">${c.releases.items.map(r => `<details class="release"><summary><span class="release-version">v${r.version}</span><span class="release-title">${esc(r.title)}</span><time datetime="${r.date}">${date(r.date)}</time>${plus}</summary><div class="release-body"><p>${esc(r.text)}</p></div></details>`).join('')}</div>${link(source + '/blob/main/CHANGELOG.md', c.releases.full, 'text-link', true)}</section>
    <section class="faq-section section" id="questions"><div class="wrap faq-grid"><div>${eyebrow(c.faq.eyebrow)}<h2>${esc(c.faq.title)}</h2></div><div class="faq-list">${c.faq.items.map(f => `<details class="faq"><summary>${esc(f.q)}${plus}</summary><p>${esc(f.a)}</p></details>`).join('')}</div></div></section>
    <section class="support-section" id="support"><div class="wrap support-inner"><div>${eyebrow(c.support.eyebrow)}<h2>${lines(c.support.title)}</h2></div><div class="support-copy"><p>${esc(c.support.text)}</p><div class="support-actions">${config.leetchiUrl ? link(config.leetchiUrl, c.support.primary, 'button button-light', true) : ''}${link(source, c.support.secondary, 'support-source', true)}</div><small>${esc(c.support.note)}</small></div></div></section>`;
  } else if (kind === 'archive') {
    main = `<section class="archive section wrap">${eyebrow(c.journal.eyebrow)}<h1>${esc(c.journal.archiveTitle)}</h1><p class="archive-intro">${esc(c.journal.archiveIntro)}</p><div class="news-list">${c.news.map(newsRow).join('')}</div></section>`;
  } else if (kind === 'article') {
    const index = c.news.indexOf(article);
    const next = c.news[(index + 1) % c.news.length];
    const readingTime = Math.max(2, Math.ceil(article.paragraphs.join(' ').split(/\s+/).length / 190));
    main = `<article class="article-page"><div class="article-masthead"><div class="article-wrap"><a class="back-link" href="${journalUrl}">${arrow}${esc(c.journal.back)}</a><div class="article-meta"><span>${esc(article.category)}</span><time datetime="${article.date}">${date(article.date)}</time><span>${readingTime} ${esc(c.journal.minutes)}</span></div><h1>${esc(article.title)}</h1><p class="article-summary">${esc(article.summary)}</p><div class="article-milestone">${esc(article.milestone)}</div></div></div><div class="article-wrap article-body">${article.paragraphs.map(p => `<p>${esc(p)}</p>`).join('')}<aside class="article-boundary"><h2>${esc(c.journal.boundary)}</h2><p>${esc(article.boundary)}</p>${link(source + '/blob/main/STATUS.md', c.journal.source, 'text-link', true)}</aside><div class="article-next">${eyebrow(c.journal.related)}<h2>${link(newsUrl(next.slug), next.title)}</h2></div></div></article>`;
  } else {
    main = `<section class="not-found section wrap">${eyebrow(c.notFound.eyebrow)}<h1>${lines(c.notFound.title)}</h1><p>${esc(c.notFound.text)}</p>${link(home, c.notFound.link, 'button button-blue')}</section>`;
  }
  return `<!doctype html>
<html lang="${c.lang}" id="top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#0b1530"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="en" href="${new URL(route, config.siteUrl).href}"><link rel="alternate" hreflang="fr" href="${new URL('fr/' + route, config.siteUrl).href}"><link rel="alternate" hreflang="x-default" href="${new URL(route, config.siteUrl).href}"><meta property="og:type" content="${kind === 'article' ? 'article' : 'website'}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:locale" content="${c.lang === 'fr' ? 'fr_FR' : 'en_GB'}"><link rel="icon" href="${root}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${asset('css')}"><script src="${asset('js')}" defer></script>${kind === '404' ? '<meta name="robots" content="noindex">' : ''}</head><body class="page-${kind}"><a class="skip-link" href="#main-content">${esc(c.nav.skip)}</a>${header}<main id="main-content">${main}</main>${footer}</body></html>`;
}
